### ISSUE TITLE
ADB configuration

### ISSUE THREAD

**Issue by Leatherface75** [Drakulix/googlehome#1]
Seems it doesn't accept adb configuration for me.

`Invalid config for [googlehome]: [adb_host] is an invalid option for [googlehome]. Check: googlehome->googlehome->adb_host. (See /config/configuration.yaml, line 1073). Please check the docs at https://home-assistant.io/components/googlehome/`

In configuration.yaml
```
  adb_host: 127.0.0.1
  adb_port: 5037
  adb_device: 192.168.0.80:5555
```

adb server bridge installed in hassio.

**Comment by Drakulix** [comment]
This should work, I am a little bit confused to why it does not.
But you may ignore the adb_host and adb_port config in your case because those are the defaults.

**Comment by Drakulix** [comment]
Can you post your complete googlehome: config?

**Comment by Leatherface75** [comment]
I am also confused because i can see those options in __init__.py file.

Already removed the configuration but it was something like this.
The only difference is those 3 added adb lines and IP to real googlehome instead of my ghproxys.
```
googlehome:
  adb_host: 127.0.0.1
  adb_port: 5037
  adb_device: 192.168.0.80:5555
  devices:
  - host: 192.168.0.15
    track_alarms: true
    rssi_threshold: -65
  - host: 192.168.0.30
    track_alarms: true
    rssi_threshold: -65
  - host: 192.168.0.70
    track_alarms: true
    rssi_threshold: -65
```

Maybe works better after some coffee.
